// transcript.rs
//
// 解析 Claude Code session jsonl 的「單行事件」，抽出真正是使用者手打的文字。
// jsonl 的格式知識（user 行、queue-operation、被塞進 user 輪的機器文字…）
// 全部關在這個模組裡；監看端（main）和選單預覽（picker）都只用
// extract_user_text 這一個函式。

use serde::Deserialize;

// ── jsonl 每行的結構 ───────────────────────────────────────────
// Claude Code 的 jsonl 一行是一個事件。我們只在意 type == "user" 的行，
// 而且 message.content 可能是純字串，也可能是一個 content-block 陣列
// （工具結果就是塞在陣列裡的 tool_result，要濾掉）。

#[derive(Deserialize)]
struct Line {
    #[serde(rename = "type")]
    kind: Option<String>,
    message: Option<Message>,
    // 你「打字中被插入」的排隊訊息不會存成 user 行，而是 type == "queue-operation"：
    // operation 為 enqueue/remove/dequeue，排隊的原文放在頂層的 content 欄位。
    operation: Option<String>,
    content: Option<String>,
}

#[derive(Deserialize)]
struct Message {
    role: Option<String>,
    content: Option<Content>,
}

// content 可能是字串，也可能是區塊陣列 —— 用 untagged 兩種都吃
#[derive(Deserialize)]
#[serde(untagged)]
enum Content {
    Text(String),
    Blocks(Vec<Block>),
}

#[derive(Deserialize)]
struct Block {
    #[serde(rename = "type")]
    kind: Option<String>,
    text: Option<String>,
}

/// 從一行 jsonl 抽出「真正是你手打的文字」，濾掉工具結果等雜訊。
/// 回傳 None 代表這行不是你打的 prompt（該跳過）。
pub fn extract_user_text(raw: &str) -> Option<String> {
    let line: Line = serde_json::from_str(raw).ok()?;

    let text = match line.kind.as_deref() {
        // 一般（送出時螢幕上打的）prompt：存成 user 行，文字在 message.content。
        Some("user") => {
            let msg = line.message?;
            if msg.role.as_deref() != Some("user") {
                return None;
            }
            match msg.content? {
                Content::Text(s) => s,
                Content::Blocks(blocks) => {
                    // 只收 type == "text" 的區塊；tool_result 之類直接略過
                    let mut buf = String::new();
                    for b in blocks {
                        if b.kind.as_deref() == Some("text") {
                            if let Some(t) = b.text {
                                buf.push_str(&t);
                                buf.push('\n');
                            }
                        }
                    }
                    buf
                }
            }
        }
        // 排隊訊息（打字中被插入的話）不會變成 user 行，而是 queue-operation。
        // 只在 enqueue 取一次（remove/dequeue 會重複）；content 就是排隊的原文。
        // 不撈這裡，這些 mid-turn 排隊的句子就會整句漏掉、永遠不講評。
        Some("queue-operation") => {
            if line.operation.as_deref() != Some("enqueue") {
                return None;
            }
            let c = line.content?;
            // 排隊的若是 slash command（/loop、/commit…）就不是英文句子，跳過。
            if c.trim_start().starts_with('/') {
                return None;
            }
            c
        }
        _ => return None,
    };

    let text = text.trim().to_string();
    if text.is_empty() {
        return None;
    }
    // Claude Code 會把很多「機器產生的文字」也塞進 user 這一輪：
    // 中斷標記、system-reminder、slash command 展開、local command 輸出…
    // 這些都含英文字母、會騙過下面的字母檢查，送給模型就會回「這不是 prompt」。
    // 出現任何一個標記就整行跳過。
    const INJECTED_MARKERS: &[&str] = &[
        "[Request interrupted",
        "<system-reminder>",
        "<command-name>",
        "<command-message>",
        "<command-args>",
        "<local-command-stdout>",
        "Caveat: The messages below were generated by the user while running local commands",
        "This is how Claude Code surfaces messages",
    ];
    if INJECTED_MARKERS.iter().any(|m| text.contains(m)) {
        return None;
    }
    // 沒有任何一個 ASCII 英文字母就當作純中文/純指令，跳過
    if !text.chars().any(|c| c.is_ascii_alphabetic()) {
        return None;
    }
    Some(text)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn user_line_with_string_content() {
        let raw = r#"{"type":"user","message":{"role":"user","content":"fix the bug please"}}"#;
        assert_eq!(extract_user_text(raw).as_deref(), Some("fix the bug please"));
    }

    #[test]
    fn multiline_and_numbered_list_kept_whole() {
        // 多行、條列式的 prompt 必須整段留住，不能只剩第一行
        let raw = r#"{"type":"user","message":{"role":"user","content":"First line.\n1. point one\n2. point two"}}"#;
        assert_eq!(
            extract_user_text(raw).as_deref(),
            Some("First line.\n1. point one\n2. point two")
        );
    }

    #[test]
    fn block_content_keeps_text_and_drops_tool_result() {
        let raw = r#"{"type":"user","message":{"role":"user","content":[
            {"type":"tool_result","content":"noise"},
            {"type":"text","text":"real prompt here"}
        ]}}"#;
        assert_eq!(extract_user_text(raw).as_deref(), Some("real prompt here"));
    }

    #[test]
    fn queue_enqueue_taken_once() {
        let enq = r#"{"type":"queue-operation","operation":"enqueue","content":"queued words"}"#;
        let deq = r#"{"type":"queue-operation","operation":"dequeue","content":"queued words"}"#;
        assert_eq!(extract_user_text(enq).as_deref(), Some("queued words"));
        assert_eq!(extract_user_text(deq), None);
    }

    #[test]
    fn queued_slash_command_skipped() {
        let raw = r#"{"type":"queue-operation","operation":"enqueue","content":"/commit now"}"#;
        assert_eq!(extract_user_text(raw), None);
    }

    #[test]
    fn injected_marker_skipped() {
        let raw = r#"{"type":"user","message":{"role":"user","content":"<system-reminder>stuff</system-reminder>"}}"#;
        assert_eq!(extract_user_text(raw), None);
    }

    #[test]
    fn pure_chinese_skipped() {
        let raw = r#"{"type":"user","message":{"role":"user","content":"純中文的訊息"}}"#;
        assert_eq!(extract_user_text(raw), None);
    }

    #[test]
    fn assistant_line_skipped() {
        let raw = r#"{"type":"assistant","message":{"role":"assistant","content":"model reply"}}"#;
        assert_eq!(extract_user_text(raw), None);
    }
}
